import { ArrowUpRight, MoreHorizontal } from "lucide-react";

const transactions = [
  { id: "#SAL-1048", name: "Al-Madina Traders", type: "Sale", quantity: "120 bags", amount: "Rs. 324,000", status: "Paid", initials: "AM" },
  { id: "#PUR-0872", name: "Punjab Rice Mills", type: "Purchase", quantity: "200 bags", amount: "Rs. 488,000", status: "Pending", initials: "PR" },
  { id: "#SAL-1047", name: "Bismillah Store", type: "Sale", quantity: "75 bags", amount: "Rs. 187,500", status: "Paid", initials: "BS" },
  { id: "#SAL-1046", name: "Faisal Enterprises", type: "Sale", quantity: "150 bags", amount: "Rs. 405,000", status: "Partial", initials: "FE" },
];

const statusStyle = { Paid: "bg-emerald-50 text-emerald-700 dark:bg-emerald-500/10 dark:text-emerald-400", Pending: "bg-amber-50 text-amber-700 dark:bg-amber-500/10 dark:text-amber-400", Partial: "bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-400" };

export default function RecentTransactions() { return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center justify-between p-5 sm:p-6"><div><h2 className="font-semibold">Recent transactions</h2><p className="mt-1 text-sm text-slate-500">Latest purchases and sales activity</p></div><button className="inline-flex items-center gap-1 text-sm font-semibold text-emerald-600 hover:text-emerald-700">View all <ArrowUpRight size={15} /></button></div><div className="overflow-x-auto"><table className="w-full min-w-[700px] text-left text-sm"><thead className="border-y border-slate-100 bg-slate-50/80 text-xs font-semibold uppercase tracking-wide text-slate-500 dark:border-slate-800 dark:bg-slate-800/30"><tr><th className="px-6 py-3">Party</th><th className="px-4 py-3">Reference</th><th className="px-4 py-3">Type</th><th className="px-4 py-3">Quantity</th><th className="px-4 py-3">Amount</th><th className="px-4 py-3">Status</th><th className="px-4 py-3" /></tr></thead><tbody>{transactions.map((item) => <tr key={item.id} className="border-b border-slate-100 last:border-0 dark:border-slate-800"><td className="px-6 py-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-slate-100 text-xs font-bold text-slate-600 dark:bg-slate-800 dark:text-slate-300">{item.initials}</span><span className="font-medium">{item.name}</span></div></td><td className="px-4 py-4 font-mono text-xs text-slate-500">{item.id}</td><td className="px-4 py-4">{item.type}</td><td className="px-4 py-4">{item.quantity}</td><td className="px-4 py-4 font-semibold">{item.amount}</td><td className="px-4 py-4"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusStyle[item.status as keyof typeof statusStyle]}`}>{item.status}</span></td><td className="px-4 py-4"><button aria-label={`Options for ${item.id}`} className="rounded-lg p-1 text-slate-400 hover:bg-slate-100 dark:hover:bg-slate-800"><MoreHorizontal size={18} /></button></td></tr>)}</tbody></table></div></section>; }
